language: r

cache: packages
sudo: required
warnings_are_errors: false

r_binary_packages:
  - ade4
  - ape
  - geometry
  - geoscale
  - geiger
  - mnormt
  - paleotree
  - phangorn
  - phyclust
  - vegan
  - covr

r:
- release

# Fix magick bug
addons:
 apt:
   update: true
   sources:
     - sourceline: 'ppa:opencpu/imagemagick'
   packages:
     - libmagick++-dev

branches:
  only:
    - master
    - release
  except:
    - CRAN

# Code coverage
r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov(token = "5f041826-63f1-47fa-b4a8-9a32633f47fa")'
