language: r
warnings_are_errors: false

branches:
  only:
    - model-test2
    - master
    - release
  except:
    - CRAN

# Code coverage
r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
